### ISSUE TITLE
Use a `environment.yaml` file

### ISSUE THREAD

**Issue by Peque** [tox-dev/tox-conda#13]
I already have all the dependencies and channels declared in an `environment.yaml` file. With Conda, I can create the environment with `conda env create -f environment.yaml`.

I think that is not currently possible with `tox-conda`, right? If so, it would be great to have that. In example:

```
[testenv]
conda_env = environment.yaml
```

Or:

```python
conda_deps =
    -fenvironment.yaml
```

Which is more aligned with the Tox-supported:

```python
deps =
    -rrequirements.txt
```

**Comment by mforbes** [comment]
This is kind of key as it is good practise to specify dependencies in an `environment.yml` file to avoid redundancy.

**Comment by mivade** [comment]
This would be really nice to have!

**Comment by jasonhuling** [comment]
This can _kind of_ be done... but in an incomplete an hacky way. Incomplete in that it does not utilize a complete `environment.yaml` file, but instead a `requirements.txt` file containing the conda dependencies you want to install. I'm still mentioning it here because it can help to remove some redundancy.

I've done something like the following:
```
[testenv]
conda_channels = 
  conda-forge
  anaconda
conda_deps = 
  pip
  --file=../requirements.conda.txt
deps =
  -rrequirements.pip.txt
commands =
```
It seems as though `conda_deps` are just passed directly to `conda install` which can accept the `--file` option. A couple things to note though:
1. The command is executed from the `.tox` subdirectory, so you need to backup with `../` so that `conda install` finds the file.
2. If you want to also pass any packages directly to `conda_deps` you need to pass them before `--file`, in this case `pip`.

Hope this helps, but built in support would be nice!

**Comment by mivade** [comment]
@jasonhuling that's a great suggestion, thanks!

For a little context, one of the annoying things about conda is that there are at least 3 ways of specifying dependencies:
- `environment.yml` files which are used by the `conda env create` command
- Regular txt files which are used by the `conda create` or `conda install` commands
- `meta.yaml` files which are used when building conda packages

Given this I think it makes more sense to just support one of these and the suggestion of using `--file` in the `conda` section is probably the easiest. Having this documented as an example in the README would be really useful.
