### ISSUE TITLE
Behavior for relative paths in `environment.yml` changed.

### ISSUE THREAD

**Issue by tobiasraabe** [tox-dev/tox-conda#143]
Hi,

thanks for the package! Unfortunately, the new release broke my setup. The folder structure looks roughly like this

```
- docs
  - rtd_environment.yml
- tox.ini
- src
  - package
```

I use `rtd_environment.yml` in my `tox.ini` to create the environment for the documentation. The env file contains a pip section to install the package from the repo.

```
...
- dependencies:
  ...
  - pip:
    - -e ../
```

With v0.10.0 the pip command fails. It says the directory does not contain a `setup.py` or `pyproject.toml`
. Everything works with v0.9.2.

The issue can be reproduced in this repo (https://github.com/pytask-dev/pytask/tree/e3c1a4cf6935a0c5cf14267acf9b5597261b3a7f) by typing `tox -e sphinx`.

**Comment by AntoineD** [comment]
@AdrianFreundQC would you mind to have a look? May be the python package should not be appended blindly to the yaml?

**Comment by AdrianFreundQC** [comment]
The problem is probably that the new version creates a temporary environment file with python appended that gets placed in the system temp directory. Because the temporary env file is in a different directory the relative paths break. Should be an easy fix by placing the temporary env in the directory the original env was in.

I'll create a PR.
