### ISSUE TITLE
cowardly refusing to delete `envdir` (it does not look like a virtualenv)

### ISSUE THREAD

**Issue by smarie** [tox-dev/tox-conda#25]
I got this error when using `tox-conda` 0.2.0 with `tox` 3.13.2, on miniconda3 with conda 4.6.14, when an environment exists and needs to be recreated:

```
(tools_py37) C:\_dev\python_ws\_Libs_OpenSource\py-make>tox -r
GLOB sdist-make: C:\_dev\python_ws\_Libs_OpenSource\py-make\setup.py
py26 create: C:\_dev\python_ws\_Libs_OpenSource\py-make\.tox\py26
ERROR: cowardly refusing to delete `envdir` (it does not look like a virtualenv): C:\_dev\python_ws\_Libs_OpenSource\py-make\.tox\py26
```

Note that even using `tox -r` does not solve the problem.

Any idea why this happens ?
Thanks for this project !

**Comment by gaborbernat** [comment]
This is a false positive from https://github.com/tox-dev/tox/pull/1340 (I'm more and more sure we should drop that check) @asottile?

**Comment by asottile** [comment]
I strongly think we should keep the check -- we just need to fix the edge cases, @smarie can you show the contents of that directory?

**Comment by asottile** [comment]
tox also doesn't support python 2.6 any more so it's probably that?

**Comment by gaborbernat** [comment]
This is a conda environment, the content of the directory will be probably mostly empty (as the python files may be in a different location). If anything the check should be something like we have the tox directories (tmp + log). All other folders may or may not be present.

**Comment by asottile** [comment]
ah so it's a plugin doing this -- perhaps we should make the check pluggable and then `tox-conda` can override it with its own behaviour

I really do think guarding ~essentially `rm -rf` is very important to tox's execution

**Comment by gaborbernat** [comment]
I feel like we're fixing imaginary issues now that causes more trouble than worth. tox has been fine without this check for quite a while now 🤔 this is the third time I've run into this in the last month 😢 since we've added it

**Comment by smarie** [comment]
Actually I can't show the contents: I removed the folder locally, reinstalled miniconda as it was corrupted, and now the error does not seem to happen anymore.
Maybe this is link to the fact that I launched tox from within pycharm? Or to the fact that I interrupted it using CTRL+C ?

If I find a reproducible pattern I will let you know

**Comment by asottile** [comment]
@gaborbernat it has also exposed bugs in user setups -- like blowing away tox's `dist` dir by a poorly named environment

**Comment by gaborbernat** [comment]
There's a much more robust simple check for that though 👍

**Comment by asottile** [comment]
sure but there's no robust check from `envdir=/home` or `envdir=src` or `envdir=../`

**Comment by rpkilby** [comment]
> sure but there's no robust check from `envdir=/home` or `envdir=src` or `envdir=../`

We could prevent users from writing to paths outside of the `.tox` directory.

----

Taking a step back, what is the goal of the `cowardly` check? As far as I can tell, it's to prevent users from creating test envs that accidentally clobber tox's working directories (`dist`, `log`, etc..), as well as directories outside of tox (`/home`, `../`, ...). If that's the case, I think there's a simpler solution.

1. Move test envs into a subdirectory so that their paths don't conflict with the other directories. My current workaround is to set `envdir={toxworkdir}/v/{envname}`. Alternatively, test envs could still be located in `.tox`, and all other work directories could be moved under `.tox/.work` or similar.
2. Check that the `envdir` doesn't write outside of `.tox`.

**Comment by asottile** [comment]
Lots use `envdir=venv` and the `--devenv` feature in the latest release encourages creating temporary environments outside of `.tox`

**Comment by rpkilby** [comment]
> it has also exposed bugs in user setups -- like blowing away tox's dist dir by a poorly named environment

It's an implementation detail of tox that causes the conflict. I'd argue that `dist` should be a valid env name.  Per point 1 in my previous comment, this could be solved if the work dirs and test env dirs were located in separate subdirectories.

----

> Lots use `envdir=venv`

I mean, the question is what kind of guardrails you want to put up. It's easy to say something categorical like "writing outside of `.tox` is potentially hazardous, do this at your own risk". It's harder to reliably guess whether or not a directory is a virtual env, as demonstrated by the various issues that have cropped up. I would rather go with the categorical approach, and allow users an option to override.

> the `--devenv` feature in the latest release encourages creating temporary environments outside of `.tox`

Sure, and `devenv` could override this check, given that a user is explicitly providing the path. If the path exists and is not empty, `devenv` could prompt the user for action. 

----

Regardless of the details, I still ask what the reason is for having the `cowardly` check. Env detection is never going to be perfectly reliable, and there may be better ways to achieve the same goal.

**Comment by gaborbernat** [comment]
So what if tox before generating an environment puts a marker file in the folder and we check for the existence of this marker file?

**Comment by asottile** [comment]
seems fine, but wouldn't it hit trouble rolling forward?

**Comment by gaborbernat** [comment]
Why would it?🤔

**Comment by asottile** [comment]
- tox==old
- tox -e py27
- makes `.tox/py27` (no marker)
- pip install tox --upgrade
- tox==new
- tox -r -e py27
- => no marker (boom)

**Comment by gaborbernat** [comment]
Not a problem if we make the marker file the .tox-config1 we already write 👍

**Comment by asottile** [comment]
:shipit:

**Comment by obestwalter** [comment]
> (I'm more and more sure we should drop that check) 

If this feature causes too much trouble, I don't think the answer is to make it less safe.

I'd rather drop the feature rather than risking deletion of arbitrary directories due to user error. We can't protect people from putting an `rm -rf {toxinidir}` in their commands, but we should try to make the tool reasonably safe. tox is not only meant for people who exactly what they are doing. I think, they should be protected as good as we can.

**Comment by obestwalter** [comment]
> So what if tox before generating an environment puts a marker file in the folder and we check for the existence of this marker file?

Sorry - didn't see that on first skim. I like that - that would be a nice explicit way :)
